---

services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=strongpassword
    volumes:
      - ./minio/data:/data
      - ./minio/config.env:/etc/config.env
    command: server --console-address ":9090" /data

  fastapi:
    build: ./api
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - minio
    environment:
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=strongpassword
      - BUCKET_NAME=uploads