---

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9500:9000"
      - "9501:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: strongpassword
    command: server /data --console-address ":9001"

  minio-api:
    build: .
    container_name: minio-api
    restart: always
    depends_on:
      - minio
    ports:
      - "8000:8000"
    environment:
      MINIO_URL: "http://minio:9000"
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "strongpassword"
      BUCKET_NAME: "uploads"

volumes:
  minio_data: