---

services:
  minio:
    build: ./minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=strongpassword
    volumes:
      - ./minio/data:/data
      - ./minio/certs:/etc/nginx/certs

  fastapi:
    build: ./api
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - minio
      - redis
    environment:
      - MINIO_URL=https://minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=strongpassword
      - BUCKET_NAME=uploads

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      minio:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./minio/certs:/etc/nginx/certs

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - minio