version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    volumes:
      - /home/bucket:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: strongpassword
    ports:
      - "9500:9000"   # Porta externa 9500 mapeada para a porta 9000 do container
      - "9501:9001"   # Console do MinIO
    command: server /data --console-address ":9001"
    restart: always

  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "until mc alias set localminio http://minio:9000 admin strongpassword; do sleep 2; done;
                  mc mb localminio/uploads || echo 'Bucket uploads já existe';
                  mc policy set public localminio/uploads;
                  sleep 2"
    restart: "no"

  api:
    build: ./api
    container_name: minio-api
    environment:
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: strongpassword
      BUCKET_NAME: uploads
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - minio
      - redis
      - minio-init
    ports:
      - "8000:8000"
    restart: always

  worker:
    build: ./api
    container_name: celery_worker
    environment:
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: strongpassword
      BUCKET_NAME: uploads
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - minio
      - redis
      - minio-init
    command: celery -A main.celery_app worker --loglevel=info
    restart: always

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always